// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: internal/beeps/beeper.proto

package beeps

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type BeepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	RequestId string               `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *BeepRequest) Reset() {
	*x = BeepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_beeps_beeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeepRequest) ProtoMessage() {}

func (x *BeepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_beeps_beeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeepRequest.ProtoReflect.Descriptor instead.
func (*BeepRequest) Descriptor() ([]byte, []int) {
	return file_internal_beeps_beeper_proto_rawDescGZIP(), []int{0}
}

func (x *BeepRequest) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BeepRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BeepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	RequestId string               `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *BeepResponse) Reset() {
	*x = BeepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_beeps_beeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeepResponse) ProtoMessage() {}

func (x *BeepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_beeps_beeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeepResponse.ProtoReflect.Descriptor instead.
func (*BeepResponse) Descriptor() ([]byte, []int) {
	return file_internal_beeps_beeper_proto_rawDescGZIP(), []int{1}
}

func (x *BeepResponse) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BeepResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_internal_beeps_beeper_proto protoreflect.FileDescriptor

var file_internal_beeps_beeper_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x65, 0x65, 0x70, 0x73,
	0x2f, 0x62, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x65, 0x65, 0x70, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x0b, 0x42, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0c, 0x42, 0x65, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x32, 0x42, 0x0a, 0x0d, 0x42, 0x65, 0x65, 0x70, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x70, 0x12, 0x12, 0x2e, 0x62, 0x65,
	0x65, 0x70, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x73, 0x73, 0x65, 0x6f, 0x62, 0x72, 0x69, 0x65, 0x6e,
	0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x65, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x65, 0x65, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_beeps_beeper_proto_rawDescOnce sync.Once
	file_internal_beeps_beeper_proto_rawDescData = file_internal_beeps_beeper_proto_rawDesc
)

func file_internal_beeps_beeper_proto_rawDescGZIP() []byte {
	file_internal_beeps_beeper_proto_rawDescOnce.Do(func() {
		file_internal_beeps_beeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_beeps_beeper_proto_rawDescData)
	})
	return file_internal_beeps_beeper_proto_rawDescData
}

var file_internal_beeps_beeper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_beeps_beeper_proto_goTypes = []interface{}{
	(*BeepRequest)(nil),         // 0: beeps.BeepRequest
	(*BeepResponse)(nil),        // 1: beeps.BeepResponse
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_internal_beeps_beeper_proto_depIdxs = []int32{
	2, // 0: beeps.BeepRequest.time:type_name -> google.protobuf.Timestamp
	2, // 1: beeps.BeepResponse.time:type_name -> google.protobuf.Timestamp
	0, // 2: beeps.BeepCollector.Beep:input_type -> beeps.BeepRequest
	1, // 3: beeps.BeepCollector.Beep:output_type -> beeps.BeepResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_beeps_beeper_proto_init() }
func file_internal_beeps_beeper_proto_init() {
	if File_internal_beeps_beeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_beeps_beeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_beeps_beeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_beeps_beeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_beeps_beeper_proto_goTypes,
		DependencyIndexes: file_internal_beeps_beeper_proto_depIdxs,
		MessageInfos:      file_internal_beeps_beeper_proto_msgTypes,
	}.Build()
	File_internal_beeps_beeper_proto = out.File
	file_internal_beeps_beeper_proto_rawDesc = nil
	file_internal_beeps_beeper_proto_goTypes = nil
	file_internal_beeps_beeper_proto_depIdxs = nil
}
